FROM nginx:alpine

COPY ./nginx/conf.d/nginx.conf /etc/nginx/nginx.conf

COPY ./www/404.html /usr/share/nginx/html/404.html
COPY ./www/50x.html /usr/share/nginx/html/50x.html
COPY ./www/index.html /usr/share/nginx/html/index.html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
