services:
  beyoutique-crm:
    image: beyoutique-crm
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    depends_on:
      - db
      - minio
    networks:
      - tardis_network
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - PORT=8080
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "30"

  beyoutique-payment-gate:
    image: beyoutique-payment-gate
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
    depends_on:
      - db
    networks:
      - tardis_network
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - PORT=${PORT}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "30"

  beyoutique-telemetrist:
    image: beyoutique-telemetrist
    ports:
      - target: 8199
        published: 8199
        protocol: tcp
        mode: host
    networks:
      - tardis_network
    environment:
      - PORT=8199
      - TELEMETRIST_ENABLED=true
      - TELEMETRIST_INTERVAL=60
      - TELEMETRIST_METRICS_PORT=8199
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "30"

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
      - ./postgres/config/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    depends_on:
      - minio
    networks:
      - tardis_network
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "30"

  nginx:
    image: beyoutique-nginx
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./www:/var/www/html
    depends_on:
      - db
      - beyoutique-crm
    networks:
      - tardis_network
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "30"

  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    volumes:
      - minio_data:/data
    networks:
      - tardis_network
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "30"

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dozzle-data:/data
    ports:
      - target: 8080
        published: 9999
        protocol: tcp
        mode: host
    networks:
      - tardis_network
    environment:
      DOZZLE_AUTH_PROVIDER: simple
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "30"

networks:
  tardis_network:
    name: tardis_shared_network
    driver: bridge
    external: true

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local

secrets:
  dozzle-users:
    file: ./dozzle-users.yml
