services:
  beyoutique-crm:
    image: beyoutique-crm
    ports:
      - 8080:8080
    depends_on:
      - db
      - minio
    networks:
      - tardis_network
    restart: unless-stopped
    deploy:
      labels:
        - "logging=loki"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
      - ./postgres/config/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - 5432:5432
    depends_on:
      - minio
    networks:
      - tardis_network
    restart: unless-stopped
    deploy:
      labels:
        - "logging=loki"

  nginx:
    image: beyoutique-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./www:/var/www/html
    depends_on:
      - db
      - beyoutique-crm
    networks:
      - tardis_network
    restart: unless-stopped
    deploy:
      labels:
        - "logging=loki"

  minio:
    image: minio/minio
    container_name: minio-storage
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    networks:
      - tardis_network
    restart: unless-stopped
    deploy:
      labels:
        - "logging=loki"

networks:
  tardis_network:
    name: tardis_shared_network
    driver: bridge
    external: true

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local
