services:
  beyoutique-crm:
    build:
      context: ../beyoutique-monolith
      dockerfile: Dockerfile
    ports:
      - "8080:8081"
    depends_on:
      - db
      - nginx
      - minio
    networks:
      - tardis_network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: tardis_db
      POSTGRES_USER: ${POSTGRES_USER:-tardis_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tardis_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tardis_network
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./www:/var/www/html
    depends_on:
      - db
    networks:
      - tardis_network
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: minio_storage
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio_user}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio_password}
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - tardis_network
    restart: unless-stopped

networks:
  tardis_network:
    name: tardis_shared_network
    driver: bridge
    external: true

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local
