auth_enabled: false

server:
  http_listen_port: 3100

common:
  instance_interface_names:
    - "lo"

ingester:
  lifecycler:
    ring:
      instance_interface_names:
        - "lo"
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  max_chunk_age: 1h
  chunk_retain_period: 30s
  max_transfer_retries: 0
schema_config:
  configs:
    - from: 2022-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/cache
    shared_store: filesystem
  filesystem:
    directory: /tmp/loki/chunks
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
table_manager:
  retention_deletes_enabled: false
  retention_period: 0
compactor:
  working_directory: /var/loki/compactor