auth_enabled: false

server:
  http_listen_port: 3100
  http_server_read_timeout: 300s # Increased from 60s to handle longer request timeouts
  http_server_write_timeout: 300s # Increased from 60s to handle longer response timeouts
  grpc_server_max_recv_msg_size: 104857600 # Increased to 100MB
  grpc_server_max_send_msg_size: 104857600 # Increased to 100MB

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  max_chunk_age: 1h
  chunk_retain_period: 30s
  max_transfer_retries: 0
  wal:
    enabled: true
    dir: /loki/wal

schema_config:
  configs:
    - from: 2022-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    shared_store: filesystem
    cache_ttl: 24h
  filesystem:
    directory: /loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_entries_limit_per_query: 5000
  ingestion_rate_mb: 60 # Doubled from 30
  ingestion_burst_size_mb: 120 # Doubled from 60
  max_global_streams_per_user: 10000
  ingestion_rate_strategy: global

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h # 7 days

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 10m