server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/positions.yaml

clients:
  - url: http://beyoutique_loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: "docker-logs"
    pipeline_stages:
      - docker: {}
    static_configs:
      - targets:
          - localhost
        labels:
          job: "docker"
          __path__: /var/lib/docker/containers/*/*-json.log